/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rogojagad
 */
import java.io.IOException;
import sun.net.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
public class MulticastGUIClient extends javax.swing.JFrame {
    private MulticastSocket s;
    public MulticastClient client = new MulticastClient();
    private static String group = "224.0.0.3";
    public ButtonGroup jawaban;
    /**
     * Creates new form MulticastGUIClient
     */
    
    private void groupButton(){
        jawaban = new ButtonGroup();
        jawaban.add(optA);
        jawaban.add(optB);
        jawaban.add(optC);
        jawaban.add(optD);
        
    }
    
    public MulticastGUIClient(MulticastSocket sock) {
        initComponents();
        groupButton();
        
        this.s = sock;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askUsername = new javax.swing.JDialog();
        username = new javax.swing.JTextField();
        submitUsername = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        exitButton = new javax.swing.JButton();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        optD = new javax.swing.JRadioButton();
        kirimJawaban = new javax.swing.JButton();

        askUsername.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        askUsername.setSize(new java.awt.Dimension(400, 300));

        submitUsername.setText("Oke");
        submitUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUsernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Masukkan username anda");

        javax.swing.GroupLayout askUsernameLayout = new javax.swing.GroupLayout(askUsername.getContentPane());
        askUsername.getContentPane().setLayout(askUsernameLayout);
        askUsernameLayout.setHorizontalGroup(
            askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askUsernameLayout.createSequentialGroup()
                .addGroup(askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(askUsernameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(username))
                    .addGroup(askUsernameLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(submitUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(askUsernameLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        askUsernameLayout.setVerticalGroup(
            askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, askUsernameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(submitUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multicast Client");

        chatBox.setEditable(false);
        chatBox.setColumns(20);
        chatBox.setRows(5);
        jScrollPane1.setViewportView(chatBox);

        exitButton.setText("Keluar");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        optA.setText("A");
        optA.setEnabled(false);
        optA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAActionPerformed(evt);
            }
        });

        optB.setText("B");
        optB.setEnabled(false);

        optC.setText("C");
        optC.setEnabled(false);

        optD.setText("D");
        optD.setEnabled(false);

        kirimJawaban.setText("Kirim");
        kirimJawaban.setEnabled(false);
        kirimJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimJawabanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optB)
                            .addComponent(optA))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(optD)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(optC))))
                    .addComponent(kirimJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optA)
                    .addComponent(optC))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optB)
                    .addComponent(optD))
                .addGap(18, 18, 18)
                .addComponent(kirimJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.client.sendMessage("*CLOSE CLIENT#"+client.getNama());
        try {
            // TODO add your handling code here:
           s.leaveGroup(InetAddress.getByName(group));
        } catch (UnknownHostException ex) {
            Logger.getLogger(MulticastGUIClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MulticastGUIClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        s.close();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void optAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAActionPerformed

    private void submitUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUsernameActionPerformed
        this.client.setUsername(this.username.getText());
        
        askUsername.setEnabled(false);
        askUsername.setVisible(false);
    }//GEN-LAST:event_submitUsernameActionPerformed

    private void kirimJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimJawabanActionPerformed
        String ans;
        if(this.optA.isSelected()){
            ans = this.optA.getText();
        }else if(this.optB.isSelected()){
            ans = this.optB.getText();
        }else if(this.optC.isSelected()){
            ans = this.optC.getText();
        }else{
            ans = this.optD.getText();
        }
        
        client.sendMessage("*ANS#"+ans+"#"+client.getNama());
        
        clearChatBox();
        this.jawaban.clearSelection();
        this.chatBox.append("Anda sudah mengirim jawaban\nMenunggu soal selanjutnya...");
    }//GEN-LAST:event_kirimJawabanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MulticastGUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MulticastGUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MulticastGUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MulticastGUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MulticastGUIClient().setVisible(true);
//            }
//        });
    }
    
    public void updateChatbox(String params){
        this.chatBox.append(params);
    }
    
    public void showAskUsername(){
        this.askUsername.setEnabled(true);
        this.askUsername.setVisible(true);
    }
    
    public void clearChatBox(){
        this.chatBox.setText("");
    }
    
    public void enableOption(){
        this.kirimJawaban.setEnabled(true);
        this.optA.setEnabled(true);
        this.optB.setEnabled(true);
        this.optC.setEnabled(true);
        this.optD.setEnabled(true);
    }
    
    public void disableOption(){
        this.kirimJawaban.setEnabled(false);
        this.optA.setEnabled(false);
        this.optB.setEnabled(false);
        this.optC.setEnabled(false);
        this.optD.setEnabled(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog askUsername;
    private javax.swing.JTextArea chatBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirimJawaban;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JRadioButton optD;
    private javax.swing.JButton submitUsername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
